export const ATUALIZAR_PROJETO = 'ATUALIZAR_PROJETOS'
export const OBTER_PROJETOS ='OBTER_PROJETOS'
export const REMOVER_PROJETO = 'REMOVER_PROJETO'
export const CADASTRAR_PROJETO = 'CADASTRAR_PROJETO'